name: "Spotify to Yaml"
description: "Export a seasonal Spotify playlist to YAML."
runs:
  using: node20
  main: "dist/index.js"

inputs:
  spotify-username:
    description: Your Spotify username.
    required: true
  filename:
    description: The YAML file to write your playlists.
    default: _data/playlists.yml
  season-names:
    description: The season names in order by the season that ends in March, June, September, and then December.
    default: "Winter,Spring,Summer,Fall"
